import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {migrate,validState as validate,archiveCard,restoreCard,projectAction,visibleCard} from './model.mjs';
// Minimal DOM adapter exercises application startup and renders; not a browser test.
const nodes=new Map(),memory=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',style:{},dataset:{},children:[],classList:{add(){},remove(){},toggle(){}},setAttribute(){},getAttribute(){return ''},focus(){},select(){},querySelector:s=>node(s),querySelectorAll:()=>[],addEventListener(){}});return nodes.get(selector);}
const ctx=vm.createContext({console,crypto:webcrypto,structuredClone,migrate,validate,archiveCard,restoreCard,projectAction,visibleCard,URL,Date,Math,innerWidth:1440,localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},document:{querySelector:s=>node(s),querySelectorAll:()=>[],body:node('body'),addEventListener(){}},MutationObserver:class{observe(){}},queueMicrotask:fn=>fn(),setTimeout:()=>0,clearTimeout(){},performance:{now:()=>0}});
vm.runInContext(fs.readFileSync('app.js','utf8').replace(/^import .*\n/,''),ctx);
assert.match(node('#main').innerHTML,/我的桌面/);
assert.doesNotMatch(node('#main').innerHTML,/布置桌面|drag-destinations/);
vm.runInContext("view='thesis';render()",ctx);assert.match(node('#main').innerHTML,/当前研究/);
vm.runInContext("openDrawer('archive')",ctx);assert.match(node('#drawer-body').innerHTML,/暂无归档内容/);
vm.runInContext("archiveCard(state.cards[2],true);openDrawer('archive')",ctx);assert.match(node('#drawer-body').innerHTML,/修改开题报告/);assert.match(node('#drawer-body').innerHTML,/恢复/);
vm.runInContext("projectAction(state,'thesis','archive');openDrawer('archive')",ctx);assert.match(node('#drawer-body').innerHTML,/恢复 毕业设计/);
vm.runInContext("projectAction(state,'thesis','restore');view='thesis';openModule('当前研究')",ctx);assert.match(node('#drawer-body').innerHTML,/data-drop="module:当前研究"/);
console.log('PASS: app startup, desktop/modules render, task archive, project archive, folder opening');
// Numeric pointer regression: no browser/network is needed for coordinate math.
const events=new Map();let saves=0;
ctx.document.addEventListener=(name,fn)=>events.set(name,fn);
ctx.document.removeEventListener=(name)=>events.delete(name);
ctx.window={scrollX:0,scrollY:0,addEventListener(){},removeEventListener(){}};
ctx.requestAnimationFrame=()=>1;ctx.cancelAnimationFrame=()=>{};
ctx.getComputedStyle=()=>({getPropertyValue:()=>''});
ctx.localStorage.setItem=(k,v)=>{saves++;memory.set(k,v);};
ctx.document.body.append=()=>{};
const container={scrollLeft:0,scrollTop:0,parentElement:ctx.document.body,dataset:{drop:'zone:thesis'},classList:{add(){},remove(){},contains(){return false;}},closest(){return this;}};
ctx.document.elementsFromPoint=()=>[container];
const style={setProperty(k,v){this[k]=v;}};
const fake={dataset:{card:'',ghost:'false'},style,parentElement:container,offsetWidth:200,offsetHeight:160,querySelectorAll:()=>[],contains:()=>false,classList:{add(){},remove(){}},setPointerCapture(){},hasPointerCapture:()=>false,getBoundingClientRect:()=>({left:200,top:200,width:200,height:160}),cloneNode:()=>({style:{setProperty(){}},classList:{add(){}},setAttribute(){},removeAttribute(){},querySelectorAll:()=>[],remove(){}})};
ctx.testElement=fake;
fake.dataset.card=vm.runInContext("state.cards[2].id",ctx);
const pointer=(x,y)=>({pointerId:1,button:0,clientX:x,clientY:y,target:{closest:()=>null},stopPropagation(){},preventDefault(){}});
ctx.testDown=pointer(220,220);
vm.runInContext("drawer=null;view=null;selected=null;state.cards[2].positions={};state.cards[2].visual_dna.rotation=0;startDrag(testDown,testElement,'card')",ctx);
const before=saves;
events.get('pointermove')(pointer(224,223));assert.equal(vm.runInContext('drag',ctx),null,'5px remains a click');
events.get('pointerup')(pointer(224,223));assert.equal(saves,before,'click does not save coordinates');
vm.runInContext("startDrag(testDown,testElement,'card')",ctx);
events.get('pointermove')(pointer(520,350));assert.equal(saves,before,'move never writes storage');
events.get('pointerup')(pointer(520,350));
assert.equal(style['--x'],'300px');assert.equal(style['--y'],'130px');assert.equal(saves,before+1);
assert.equal(JSON.parse(memory.get('personal-desk-v1')).cards[2].positions.desk.x,300);
vm.runInContext("startDrag(testDown,testElement,'card')",ctx);events.get('pointermove')(pointer(580,390));events.get('pointercancel')();assert.equal(saves,before+1,'cancel retains saved position');
vm.runInContext("state.cards[2].positions={};startDrag(testDown,testElement,'card')",ctx);events.get('pointermove')(pointer(260,250));ctx.window.scrollY=100;events.get('pointerup')(pointer(260,250));assert.equal(style['--y'],'130px','window scroll is included exactly once');
console.log('PASS: drag threshold, no writes during motion, 300px movement without snapback, persisted coordinates, pointer cancellation, scroll compensation');
